# Generated by Django 4.2.11 on 2024-05-05 01:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('color', models.TextField(null=True)),
                ('logo', models.TextField(null=True)),
                ('url', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Stream',
            fields=[
                ('stream_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('stream_type', models.CharField(max_length=255)),
                ('account_id', models.CharField(max_length=255)),
                ('average_amount', models.FloatField()),
                ('category', models.JSONField()),
                ('category_id', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('first_date', models.DateField()),
                ('frequency', models.CharField(max_length=255)),
                ('is_active', models.BooleanField()),
                ('is_user_modified', models.BooleanField()),
                ('last_amount', models.FloatField()),
                ('last_date', models.DateField()),
                ('last_user_modified_datetime', models.DateTimeField()),
                ('merchant_name', models.CharField(blank=True, max_length=255)),
                ('personal_finance_category', models.JSONField()),
                ('status', models.CharField(max_length=255)),
                ('transaction_ids', models.JSONField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('transaction_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('account_id', models.CharField(max_length=255)),
                ('account_owner', models.CharField(blank=True, max_length=255)),
                ('amount', models.FloatField()),
                ('authorized_date', models.DateField()),
                ('authorized_datetime', models.DateTimeField()),
                ('category', models.JSONField()),
                ('category_id', models.CharField(blank=True, max_length=255)),
                ('check_number', models.CharField(blank=True, max_length=255)),
                ('counterparties', models.JSONField()),
                ('date', models.DateField()),
                ('datetime', models.DateTimeField()),
                ('iso_currency_code', models.CharField(max_length=3)),
                ('location', models.JSONField()),
                ('logo_url', models.CharField(blank=True, max_length=255)),
                ('merchant_entity_id', models.CharField(blank=True, max_length=255)),
                ('merchant_name', models.CharField(blank=True, max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('payment_channel', models.CharField(max_length=255)),
                ('payment_meta', models.JSONField()),
                ('pending', models.BooleanField()),
                ('pending_transaction_id', models.CharField(blank=True, max_length=255)),
                ('personal_finance_category', models.JSONField()),
                ('personal_finance_category_icon_url', models.CharField(blank=True, max_length=255)),
                ('transaction_code', models.CharField(blank=True, max_length=255)),
                ('transaction_type', models.CharField(max_length=255)),
                ('unofficial_currency_code', models.CharField(blank=True, max_length=255)),
                ('website', models.CharField(blank=True, max_length=255)),
                ('category_user', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('access_token', models.TextField()),
                ('transaction_cursor', models.TextField(blank=True)),
                ('institution', models.TextField()),
                ('status', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('available_balance', models.FloatField()),
                ('current_balance', models.FloatField()),
                ('iso_currency_code', models.CharField(max_length=3)),
                ('credit_limit', models.FloatField(null=True)),
                ('mask', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('official_name', models.CharField(blank=True, max_length=255, null=True)),
                ('subtype', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='app.item')),
            ],
        ),
    ]
