# Generated by Django 4.2.11 on 2024-05-05 01:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='institution',
            new_name='institution_id',
        ),
    ]
